/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vistas;

import Controladores.MenuControlador;
import javax.swing.JButton;

/**
 *
 * @author Sofía
 */
public class MenuVista extends javax.swing.JFrame {

    /**
     * Creates new form MenuVista
     */
    MenuControlador C_Menu;
    public MenuVista() {
        initComponents();
        C_Menu = new MenuControlador(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFileChooser1 = new javax.swing.JFileChooser();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        BTN_NOTICIAS_MENU = new javax.swing.JButton();
        BTN_REGISTRARDENUNCIA_MENU = new javax.swing.JButton();
        BTN_VERDENUNCIA_MENU = new javax.swing.JButton();
        BTN_ESTADISTICAS_MENU = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 51, 51));
        jLabel1.setText("Sistema de reporte de denuncias: LIMA Edition");

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyectofinalpooii/file.png"))); // NOI18N

        BTN_NOTICIAS_MENU.setBackground(new java.awt.Color(255, 51, 0));
        BTN_NOTICIAS_MENU.setText("NOTICIAS");
        BTN_NOTICIAS_MENU.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTN_NOTICIAS_MENUActionPerformed(evt);
            }
        });

        BTN_REGISTRARDENUNCIA_MENU.setBackground(new java.awt.Color(255, 51, 0));
        BTN_REGISTRARDENUNCIA_MENU.setText("REGISTRA TU DENUNCIA");
        BTN_REGISTRARDENUNCIA_MENU.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTN_REGISTRARDENUNCIA_MENUActionPerformed(evt);
            }
        });

        BTN_VERDENUNCIA_MENU.setBackground(new java.awt.Color(255, 51, 0));
        BTN_VERDENUNCIA_MENU.setText("VER DENUNCIAS");

        BTN_ESTADISTICAS_MENU.setBackground(new java.awt.Color(255, 51, 0));
        BTN_ESTADISTICAS_MENU.setText("VER ESTADISTICAS");
        BTN_ESTADISTICAS_MENU.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTN_ESTADISTICAS_MENUActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 102, 102));
        jLabel3.setText("MENÚ");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setText("Seleccionar la opción que desea ingresar");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(BTN_NOTICIAS_MENU, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(BTN_VERDENUNCIA_MENU, javax.swing.GroupLayout.DEFAULT_SIZE, 208, Short.MAX_VALUE))
                        .addGap(87, 87, 87)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(BTN_ESTADISTICAS_MENU, javax.swing.GroupLayout.DEFAULT_SIZE, 189, Short.MAX_VALUE)
                            .addComponent(BTN_REGISTRARDENUNCIA_MENU, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(86, 86, 86)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 273, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel1)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(10, 10, 10)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel4)
                                .addComponent(jLabel3)))))
                .addGap(0, 46, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(12, 12, 12)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 10, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(BTN_NOTICIAS_MENU, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(BTN_REGISTRARDENUNCIA_MENU, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(54, 54, 54)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(BTN_VERDENUNCIA_MENU, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(BTN_ESTADISTICAS_MENU, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(58, 58, 58))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(29, 29, 29))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BTN_NOTICIAS_MENUActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTN_NOTICIAS_MENUActionPerformed
        // TODO add your handling code here:
        C_Menu.actionPerformed(evt);
    }//GEN-LAST:event_BTN_NOTICIAS_MENUActionPerformed

    private void BTN_REGISTRARDENUNCIA_MENUActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTN_REGISTRARDENUNCIA_MENUActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BTN_REGISTRARDENUNCIA_MENUActionPerformed

    private void BTN_ESTADISTICAS_MENUActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTN_ESTADISTICAS_MENUActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BTN_ESTADISTICAS_MENUActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuVista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuVista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuVista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuVista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuVista().setVisible(true);
            }
        });
    }

    public JButton getBTN_ESTADISTICAS_MENU() {
        return BTN_ESTADISTICAS_MENU;
    }

    public void setBTN_ESTADISTICAS_MENU(JButton BTN_ESTADISTICAS_MENU) {
        this.BTN_ESTADISTICAS_MENU = BTN_ESTADISTICAS_MENU;
    }

    public JButton getBTN_NOTICIAS_MENU() {
        return BTN_NOTICIAS_MENU;
    }

    public void setBTN_NOTICIAS_MENU(JButton BTN_NOTICIAS_MENU) {
        this.BTN_NOTICIAS_MENU = BTN_NOTICIAS_MENU;
    }

    public JButton getBTN_REGISTRARDENUNCIA_MENU() {
        return BTN_REGISTRARDENUNCIA_MENU;
    }

    public void setBTN_REGISTRARDENUNCIA_MENU(JButton BTN_REGISTRARDENUNCIA_MENU) {
        this.BTN_REGISTRARDENUNCIA_MENU = BTN_REGISTRARDENUNCIA_MENU;
    }

    public JButton getBTN_VERDENUNCIA_MENU() {
        return BTN_VERDENUNCIA_MENU;
    }

    public void setBTN_VERDENUNCIA_MENU(JButton BTN_VERDENUNCIA_MENU) {
        this.BTN_VERDENUNCIA_MENU = BTN_VERDENUNCIA_MENU;
    }
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BTN_ESTADISTICAS_MENU;
    private javax.swing.JButton BTN_NOTICIAS_MENU;
    private javax.swing.JButton BTN_REGISTRARDENUNCIA_MENU;
    private javax.swing.JButton BTN_VERDENUNCIA_MENU;
    private javax.swing.JFileChooser jFileChooser1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    // End of variables declaration//GEN-END:variables
}
